use_frameworks!
inhibit_all_warnings!
platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'Example' do
  pod 'CaamDauExtension', :path => '../../Extension'
  pod 'CaamDauCompatible', :path => '../../Compatible'
  pod 'CaamDauValue', :path => '../../Value'
  pod 'CaamDauForm', :path => '../'
  
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
end
